### PR TITLE
Add property name to Media

### PR DESCRIPTION
**Pull request by saybou**
Add property name to Media in order to distinct enclosure from thumbnail.

### CODE REVIEW

**Comment by alexdebril** [comment]
Hi @saybou 

Thank you for this PR, it's an interesting feature to separate thumbnails and enclosures, so your contribution must be added to feed-io. However, I tried to figure out how other developers will react when they'll have to use it : 

```php
if ( $media->getName() === 'thumbnail') {
    // process the media as a thumbnail
}
```

It's kind of surprising to go through a comparison with a `name` attribute to get a piece of information that looks like the media's type if you think about it. It's just a semantic issue.

Maybe something more like : 

```php
if ( $media->getType() === 'thumbnail') {
    // process the media as a thumbnail
}
```
or : 

```php
if ( $media->isThumbnail() ) {
    // process the media as a thumbnail
}
```

could be more explicit.

What do you think ?

**Comment by saybou** [comment]
Hi @alexdebril 

yes you're right :smiley: 
i will commit the changes.
Type is already a property ("jpeg", ...), and yes the "isThumbnail" function could be a good thing.
What do you prefer about the property name to use instead of "name" ?

Thank you for your reply. :pray:

**Comment by alexdebril** [comment]
Hi @saybou 

You're welcome !

You're right, "type" is already taken for the mime-type, now we need to figure out something more relevant. We have two approaches : 

 - a boolean that indicates if the media is the original or a thumbnail
 - the node's name

The node's name may be cleaner : if another kind of media appears, it won't force to break the logic based on a boolean value. On the other hand, it doesn't seems likely to happen soon.

I would say : `setNodeName(? string $nodeName)` and `isThumbnail()` returns the comparison's result of : `return $this->nodeName === 'thumbnail'`

Thank you for your contribution :)

**Comment by alexdebril** [comment]
Thank you @saybou , this pull request will be included in the next release

**Pull request merged**
