### PR TITLE
Add support for image property on FeedInterface Rss / Atom (logo)

### PR DESCRIPTION
**Pull request by sylvainlg**
Add image property support for FeedInterface.

- Rss : get the image > url value
- Atom : get the logo value because it seem to be the best propety to map into image, see https://tools.ietf.org/html/rfc4287#section-4.2.8

Update documentation

Try to set some tests

### CODE REVIEW

**Comment by alexdebril** [comment]
Hi @sylvainlg

**Comment by sylvainlg** [comment]
Hi Alex,
OK i will make the change.

**Comment by sylvainlg** [comment]
Hi,
Sorry for the delay, i made the change :)

**Comment by luispabon** [comment]
Thank you for this contribution, I had also the intention of doing it but life gets in the way. Muchly appreciated :+1:

**Pull request merged**
