### PR TITLE
Fix: Relative links

### PR DESCRIPTION
**Pull request by IgorA100**
1. Fix: feed discovery with relative URLs in links
2. Fix: relative links in the Title and in Body

Example: https://k47.cz/
Solution to the problem: #417
Solution to the problem: #418

### CODE REVIEW

**Comment by IgorA100** [comment]
If there is approval, then these changes must be made to 5.3.x, which is used in Nextcloud news
I can do it myself.

**Review by alexdebril — APPROVED** [review]

**Comment by alexdebril** [comment]
Thank you very much @IgorA100 I appreciate the effort. CI is ongoing, I'll merge the PR once it's over

**Comment by IgorA100** [comment]
> I'll merge the PR once it's over

Thank you!
Can I prepare PR in 5.3.x?

**Comment by alexdebril** [comment]
> > I'll merge the PR once it's over
> 
> Thank you! Can I prepare PR in 5.3.x?

yes sure, thanks a lot!

**Pull request merged**
